import pandas as pd

def percent_to_decimal(df):
    for col in [col for col in df.columns.to_list() if df[col].dtype == 'object' and df[col].str.contains('%').any()]:
        df[col] = df[col].str.strip('%').astype('float64') / 100.0
    return df

def format_market_value(df):
    for col in [col for col in df.columns.to_list() if df[col].dtype == 'object' and df[col].str.contains(r'\$').any()]:
        df[col] = (df['DollarMV'].str.replace(r'^\(\$', '-', regex=True).str.strip(')$').astype('float64') * 10e6).astype('int64')
    return df

def team_abbreviator(df):
    df['Team'] = df['Team'].str.replace('^SDP$', 'SD', regex=True).str.replace('^SFG$', 'SF', regex=True).str.replace('^TBR$', 'TB', regex=True)
    return df

def main():
    for cat in ['batting', 'pitching']:
        dfs = []
        for i in range(2015, 2023):
            new_df = pd.read_csv(f'../data/raw/fangraphs/{cat}/fangraphs{cat}{i}raw.csv')
            new_df['Season'] = i
            dfs.append(new_df)
        df = pd.concat(dfs)
        df = df.drop('Age Rng', axis=1)
        df = df.rename({'playerid': 'fangraphsID', 'SO': 'K', 'AVG': 'BA', 'K-BB%': 'K%-BB%', 'GDP': 'GIDP', 'SH': 'SAC', 'ShO': 'SHO', 'Starting': 'SPWAR', 'Start-IP': 'SPIP', 'Relieving': 'RPWAR', 'Relief-IP': 'RPIP', 'E-F': 'ERA-FIP', 'Barrel%': 'Barrels/BBE', 'HardHit%': 'HardHit/BBE', 'Events': 'BBE', 'Dol': 'DollarMV', 'Dollars': 'DollarMV', 'AVG+': 'BA+'}, axis=1)
        df = df.rename({'GB': 'GB (bis)', 'FB': 'FB (bis)', 'LD': 'LD (bis)', 'IFFB': 'IFFB (bis)', 'Pitches': 'Pitches (bis)', 'Balls': 'Balls (bis)', 'Strikes': 'Strikes (bis)', 'IFH': 'IFH (bis)', 'BU': 'BU (bis)', 'BUH': 'BUH (bis)', 'GB/FB': 'GB/FB (bis)', 'LD%': 'LD% (bis)', 'GB%': 'GB% (bis)', 'FB%': 'FB% (bis)', 'IFFB%': 'IFFB% (bis)', 'HR/FB': 'HR/FB (bis)', 'IFH%': 'IFH% (bis)', 'BUH%': 'BUH% (bis)', 'FB%.1': 'FA% (bis)', 'FBv': 'FAv (bis)', 'SL%': 'SL% (bis)', 'SLv': 'SLv (bis)', 'CT%': 'CT% (bis)', 'CTv': 'CTv (bis)', 'CB%': 'CB% (bis)', 'CBv': 'CBv (bis)', 'CH%': 'CH% (bis)', 'CHv': 'CHv (bis)', 'SF%': 'SF% (bis)', 'SFv': 'SFv (bis)', 'KN%': 'KN% (bis)', 'KNv': 'KNv (bis)', 'XX%': 'XX% (bis)', 'PO%': 'PO% (bis)', 'wFB': 'wFA (bis)', 'wSL': 'wSL (bis)', 'wCT': 'wCT (bis)', 'wCB': 'wCB (bis)', 'wCH': 'wCH (bis)', 'wSF': 'wSF (bis)', 'wKN': 'wKN (bis)', 'wFB/C': 'wFA/C (bis)', 'wSL/C': 'wSL/C (bis)', 'wCT/C': 'wCT/C (bis)', 'wCB/C': 'wCB/C (bis)', 'wCH/C': 'wCH/C (bis)', 'wSF/C': 'wSF/C (bis)', 'wKN/C': 'wKN/C (bis)', 'O-Swing%': 'O-Swing% (bis)', 'Z-Swing%': 'Z-Swing% (bis)', 'Swing%': 'Swing% (bis)', 'O-Contact%': 'O-Contact% (bis)', 'Z-Contact%': 'Z-Contact% (bis)', 'Contact%': 'Contact% (bis)', 'Zone%': 'Zone% (bis)', 'F-Strike%': 'F-Strike% (bis)', 'SwStr%': 'SwStr% (bis)', 'Pull%': 'Pull% (bis)', 'Cent%': 'Cent% (bis)', 'Oppo%': 'Oppo% (bis)', 'Soft%': 'Soft% (bis)', 'Med%': 'Med% (bis)', 'Hard%': 'Hard% (bis)', 'LD+%': 'LD+% (bis)', 'GB%+': 'GB%+ (bis)', 'FB%+': 'FB%+ (bis)', 'HR/FB%+': 'HR/FB%+ (bis)', 'Pull%+': 'Pull%+ (bis)', 'Cent%+': 'Cent%+ (bis)', 'Oppo%+': 'Oppo%+ (bis)', 'Soft%+': 'Soft%+ (bis)', 'Med%+': 'Med%+ (bis)', 'Hard%+': 'Hard%+ (bis)'}, axis=1)
        df = df.rename({'FA% (sc)': 'FF%', 'FT% (sc)': 'FT%', 'FC% (sc)': 'FC%', 'FS% (sc)': 'FS%', 'FO% (sc)': 'FO%', 'SI% (sc)': 'SI%', 'SL% (sc)': 'SL%', 'CU% (sc)': 'CU%', 'KC% (sc)': 'KC%', 'EP% (sc)': 'EP%', 'CH% (sc)': 'CH%', 'SC% (sc)': 'SC%', 'KN% (sc)': 'KN%', 'UN% (sc)': 'UN%', 'vFA (sc)': 'vFF', 'vFT (sc)': 'vFT', 'vFC (sc)': 'vFC', 'vFS (sc)': 'vFS', 'vFO (sc)': 'vFO', 'vSI (sc)': 'vSI', 'vSL (sc)': 'vSL', 'vCU (sc)': 'vCU', 'vKC (sc)': 'vKC', 'vEP (sc)': 'vEP', 'vCH (sc)': 'vCH', 'vSC (sc)': 'vSC', 'vKN (sc)': 'vKN', 'FA-X (sc)': 'FF-X', 'FT-X (sc)': 'FT-X', 'FC-X (sc)': 'FC-X', 'FS-X (sc)': 'FS-X', 'FO-X (sc)': 'FO-X', 'SI-X (sc)': 'SI-X', 'SL-X (sc)': 'SL-X', 'CU-X (sc)': 'CU-X', 'KC-X (sc)': 'KC-X', 'EP-X (sc)': 'EP-X', 'CH-X (sc)': 'CH-X', 'SC-X (sc)': 'SC-X', 'KN-X (sc)': 'KN-X', 'FA-Z (sc)': 'FF-Z', 'FT-Z (sc)': 'FT-Z', 'FC-Z (sc)': 'FC-Z', 'FS-Z (sc)': 'FS-Z', 'FO-Z (sc)': 'FO-Z', 'SI-Z (sc)': 'SI-Z', 'SL-Z (sc)': 'SL-Z', 'CU-Z (sc)': 'CU-Z', 'KC-Z (sc)': 'KC-Z', 'EP-Z (sc)': 'EP-Z', 'CH-Z (sc)': 'CH-Z', 'SC-Z (sc)': 'SC-Z', 'KN-Z (sc)': 'KN-Z', 'wFA (sc)': 'wFF', 'wFT (sc)': 'wFT', 'wFC (sc)': 'wFC', 'wFS (sc)': 'wFS', 'wFO (sc)': 'wFO', 'wSI (sc)': 'wSI', 'wSL (sc)': 'wSL', 'wCU (sc)': 'wCU', 'wKC (sc)': 'wKC', 'wEP (sc)': 'wEP', 'wCH (sc)': 'wCH', 'wSC (sc)': 'wSC', 'wKN (sc)': 'wKN', 'wFA/C (sc)': 'wFF/C', 'wFT/C (sc)': 'wFT/C', 'wFC/C (sc)': 'wFC/C', 'wFS/C (sc)': 'wFS/C', 'wFO/C (sc)': 'wFO/C', 'wSI/C (sc)': 'wSI/C', 'wSL/C (sc)': 'wSL/C', 'wCU/C (sc)': 'wCU/C', 'wKC/C (sc)': 'wKC/C', 'wEP/C (sc)': 'wEP/C', 'wCH/C (sc)': 'wCH/C', 'wSC/C (sc)': 'wSC/C', 'wKN/C (sc)': 'wKN/C', 'O-Swing% (sc)': 'O-Swing%', 'Z-Swing% (sc)': 'Z-Swing%', 'Swing% (sc)': 'Swing%', 'O-Contact% (sc)': 'O-Contact%', 'Z-Contact% (sc)': 'Z-Contact%', 'Contact% (sc)': 'Contact%', 'Zone% (sc)': 'Zone%'}, axis=1)
        df = percent_to_decimal(df)
        df = format_market_value(df)
        df = team_abbreviator(df)
        if cat == 'batting':
            df = df[['fangraphsID', 'Name', 'Season', 'Team', 'Age', 'G', 'AB', 'PA', 'H', '1B', '2B', '3B', 'HR', 'R', 'RBI', 'BB', 'IBB', 'K', 'HBP', 'SF', 'SAC', 'GIDP', 'SB', 'CS', 'BA', 'BB%', 'K%', 'BB/K', 'OBP', 'SLG', 'OPS', 'ISO', 'BABIP', 'wOBA', 'wRAA', 'wRC', 'Bat', 'Fld', 'Rep', 'Pos', 'RAR', 'WAR', 'DollarMV', 'wRC+', 'WPA', '-WPA', '+WPA', 'RE24', 'REW', 'pLI', 'phLI', 'PH', 'WPA/LI', 'Clutch', 'BsR', 'FF%', 'FT%', 'FC%', 'FS%', 'FO%', 'SI%', 'SL%', 'CU%', 'KC%', 'EP%', 'CH%', 'SC%', 'KN%', 'UN%', 'vFF', 'vFT', 'vFC', 'vFS', 'vFO', 'vSI', 'vSL', 'vCU', 'vKC', 'vEP', 'vCH', 'vSC', 'vKN', 'FF-X', 'FT-X', 'FC-X', 'FS-X', 'FO-X', 'SI-X', 'SL-X', 'CU-X', 'KC-X', 'EP-X', 'CH-X', 'SC-X', 'KN-X', 'FF-Z', 'FT-Z', 'FC-Z', 'FS-Z', 'FO-Z', 'SI-Z', 'SL-Z', 'CU-Z', 'KC-Z', 'EP-Z', 'CH-Z', 'SC-Z', 'KN-Z', 'wFF', 'wFT', 'wFC', 'wFS', 'wFO', 'wSI', 'wSL', 'wCU', 'wKC', 'wEP', 'wCH', 'wSC', 'wKN', 'wFF/C', 'wFT/C', 'wFC/C', 'wFS/C', 'wFO/C', 'wSI/C', 'wSL/C', 'wCU/C', 'wKC/C', 'wEP/C', 'wCH/C', 'wSC/C', 'wKN/C', 'O-Swing%', 'Z-Swing%', 'Swing%', 'O-Contact%', 'Z-Contact%', 'Contact%', 'Zone%', 'Def', 'wSB', 'UBR', 'Off', 'Lg', 'wGDP', 'TTO%', 'BA+', 'BB%+', 'K%+', 'OBP+', 'SLG+', 'ISO+', 'BABIP+', 'EV', 'LA', 'Barrels', 'Barrels/BBE', 'maxEV', 'HardHit', 'HardHit/BBE', 'BBE', 'CStr%', 'CSW%', 'xBA', 'xSLG', 'xwOBA']]
        else:
            df['SVO'] = df['SV'] + df['BS']
            df = df[['fangraphsID', 'Name', 'Season', 'Age', 'W', 'L', 'ERA', 'G', 'GS', 'CG', 'SHO', 'SV', 'BS', 'IP', 'TBF', 'H', 'R', 'ER', 'HR', 'BB', 'IBB', 'HBP', 'WP', 'BK', 'K', 'RS', 'K/9', 'BB/9', 'K/BB', 'H/9', 'HR/9', 'BA', 'WHIP', 'BABIP', 'LOB%', 'FIP', 'SPWAR', 'SPIP', 'RPWAR', 'RPIP', 'RAR', 'WAR', 'DollarMV', 'tERA', 'xFIP', 'WPA', '-WPA', '+WPA', 'RE24', 'REW', 'pLI', 'inLI', 'gmLI', 'exLI', 'Pulls', 'WPA/LI', 'Clutch', 'HLD', 'SD', 'MD', 'ERA-', 'FIP-', 'xFIP-', 'K%', 'BB%', 'SIERA', 'RS/9', 'ERA-FIP', 'FF%', 'FT%', 'FC%', 'FS%', 'FO%', 'SI%', 'SL%', 'CU%', 'KC%', 'EP%', 'CH%', 'SC%', 'KN%', 'UN%', 'vFF', 'vFT', 'vFC', 'vFS', 'vFO', 'vSI', 'vSL', 'vCU', 'vKC', 'vEP', 'vCH', 'vSC', 'vKN', 'FF-X', 'FT-X', 'FC-X', 'FS-X', 'FO-X', 'SI-X', 'SL-X', 'CU-X', 'KC-X', 'EP-X', 'CH-X', 'SC-X', 'KN-X', 'FF-Z', 'FT-Z', 'FC-Z', 'FS-Z', 'FO-Z', 'SI-Z', 'SL-Z', 'CU-Z', 'KC-Z', 'EP-Z', 'CH-Z', 'SC-Z', 'KN-Z', 'wFF', 'wFT', 'wFC', 'wFS', 'wFO', 'wSI', 'wSL', 'wCU', 'wKC', 'wEP', 'wCH', 'wSC', 'wKN', 'wFF/C', 'wFT/C', 'wFC/C', 'wFS/C', 'wFO/C', 'wSI/C', 'wSL/C', 'wCU/C', 'wKC/C', 'wEP/C', 'wCH/C', 'wSC/C', 'wKN/C', 'O-Swing%', 'Z-Swing%', 'Swing%', 'O-Contact%', 'Z-Contact%', 'Contact%', 'Zone%', 'Pace', 'K%-BB%', 'kwERA', 'TTO%', 'BA+', 'WHIP+', 'BABIP+', 'LOB%+', 'K%+', 'BB%+', 'EV', 'LA', 'Barrels', 'Barrels/BBE', 'maxEV', 'HardHit', 'HardHit/BBE', 'BBE', 'CStr%', 'CSW%', 'xERA']]
        df.to_csv(f'../data/cleaned/fangraphs/{cat}/fangraphs{cat}cleaned.csv', index=False)

if __name__ == '__main__':
    main()
